cloud_migration: {  }
identifier: HIMW-141824
key: d3fea6a35c928cde850b0f16de59d1b0
subscription_data:
  active: true
  href: 'https://insight.acquia.com/node/uuid/c29068e9-50b5-4b50-ac7b-4f9bb6c86409/dashboard'
  uuid: c29068e9-50b5-4b50-ac7b-4f9bb6c86409
  subscription_name: drupalcluj
  expiration_date:
    value: '2017-12-20T00:00:00'
  product:
    view: 'Acquia Network'
  derived_key_salt: 4c0b9acb79e3de5a451800c731be4b50
  update_service: '1'
  search_service_enabled: 1
  rpc_version: '3'
  update: {  }
  heartbeat_data:
    acquia_lift:
      status: false
      decision:
        public_key: ''
        private_key: ''
      profile:
        account_name: ''
        hostname: ''
        public_key: ''
        secret_key: ''
        js_path: ''
    search_service_enabled: 1
subscription_name: drupalcluj
debug: false
cron_interval: 30
cron_interval_override: 0
banner_service: 'https://insight.acquia.com/system/acquia-banner'
migrate:
  files: 1
hide_signup_messages: 0
spi:
  server: 'https://nspi.acquia.com'
  ssl_override: false
  ssl_verify: true
  def_vars:
    preprocess_css:
      optional: 0
      description: ''
  def_waived_vars: {  }
  def_timestamp: 1374783288
  new_optional_data: 1
  admin_priv: 1
  send_node_user: 1
  send_watchdog: 1
  module_diff_data: 1
  use_cron: 1
  dynamic_banner: 0
  set_variables_override: 1
  set_variables_automatic:
    - acquia_spi_set_variables_automatic
    - error_level
    - preprocess_js
    - page_cache_maximum_age
    - block_cache
    - preprocess_css
    - page_compression
    - image_allow_insecure_derivatives
    - googleanalytics_cache
    - acquia_spi_send_node_user
    - acquia_spi_admin_priv
    - acquia_spi_module_diff_data
    - acquia_spi_send_watchdog
    - acquia_spi_use_cron
  ignored_set_variables: {  }
  saved_variables:
    variables: {  }
    time: 0
  cron_interval: 28800
  site_name: 'Drupal Community Cluj-Napoca'
  site_machine_name: drupal_community_cluj_napoca
  site_uuid: cecca960-490b-44e9-b442-b885cc1c3865
mapping:
  acquia_spi_send_node_user:
    - acquia_connector.settings
    - spi
    - send_node_user
  acquia_spi_admin_priv:
    - acquia_connector.settings
    - spi
    - admin_priv
  acquia_spi_module_diff_data:
    - acquia_connector.settings
    - spi
    - module_diff_data
  acquia_spi_send_watchdog:
    - acquia_connector.settings
    - spi
    - send_watchdog
  acquia_spi_use_cron:
    - acquia_connector.settings
    - spi
    - use_cron
  cache_backends: {  }
  cache_default_class:
    - cache_classes
    - cache
  cache_inc: {  }
  cron_safe_threshold:
    - system.cron
    - threshold
    - autorun
  googleanalytics_cache: {  }
  error_level:
    - system.logging
    - error_level
  preprocess_js:
    - system.performance
    - js
    - preprocess
  page_cache_maximum_age:
    - system.performance
    - cache
    - page
    - max_age
  block_cache: {  }
  preprocess_css:
    - system.performance
    - css
    - preprocess
  page_compression:
    - system.performance
    - response
    - gzip
  cron_last:
    - state
    - system.cron_last
  clean_url: {  }
  redirect_global_clean: {  }
  theme_zen_settings: {  }
  site_offline:
    - state
    - system.maintenance_mode
  site_name:
    - system.site
    - name
  user_register:
    - user.settings
    - register
  user_signatures:
    - user.settings
    - signatures
  user_admin_role:
    - user.settings
    - admin_role
  user_email_verification:
    - user.settings
    - verify_mail
  user_cancel_method:
    - user.settings
    - cancel_method
  filter_fallback_format:
    - filter.settings
    - fallback_format
  dblog_row_limit:
    - dblog.settings
    - row_limit
  date_default_timezone:
    - system.date
    - timezone
    - default
  file_default_scheme:
    - system.file
    - default_scheme
  install_profile:
    - settings
    - install_profile
  maintenance_mode:
    - state
    - system.maintenance_mode
  update_last_check:
    - state
    - update.last_check
  site_default_country:
    - system.date
    - country
    - default
  acquia_spi_saved_variables:
    - acquia_connector.settings
    - spi
    - saved_variables
  acquia_spi_set_variables_automatic:
    - acquia_connector.settings
    - spi
    - set_variables_automatic
  acquia_spi_ignored_set_variables:
    - acquia_connector.settings
    - spi
    - ignored_set_variables
  acquia_spi_set_variables_override:
    - acquia_connector.settings
    - spi
    - set_variables_override
  fast_404:
    - system.performance
    - fast_404
    - enabled
  allow_insecure_uploads:
    - system.file
    - allow_insecure_uploads
  http_response_debug_cacheability_headers:
    - container_parameter
    - http.response.debug_cacheability_headers
_core:
  default_config_hash: 0N5wlMbQX42onI1paJeEDU2Ap_eNZdcCVM1IPHFRHKM
