module:
  acquia_connector: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  country: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dcc_bottom_widgets: 0
  dcc_email: 0
  dcc_encryption: 0
  dcc_form_alter: 0
  dcc_gtd_registration: 0
  dcc_gtd_scheduler: 0
  dcc_multistep: 0
  dcc_seo: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entityqueue: 0
  eu_cookie_compliance: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  google_map_field: 0
  help: 0
  history: 0
  image: 0
  link: 0
  mailsystem: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  search: 0
  shortcut: 0
  swiftmailer: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  dcc: 1000
theme:
  stable: 0
  classy: 0
  dcc_theme: 0
  businessgroup_zymphonies_theme: 0
  seven: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
